// Generated by tools/gen_notify_stubs.py. DO NOT EDIT BY HAND.
#include "Modules/ModuleManager.h"

// The MODULE NAME is the whole point of this file. A montage stores its notify as
// `/Script/Hero_1047.<Class>`, and only a module actually named `Hero_1047` produces that path.
IMPLEMENT_MODULE(FDefaultModuleImpl, Hero_1047);
