// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AN_AkEventFootstep` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AN_AkEvent.h"
#include "UObject/NoExportTypes.h"
#include "AN_AkEventFootstep.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AN_AkEventFootstep"))
class MARVEL_API UAN_AkEventFootstep : public UAN_AkEvent
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bNeedZSpeedLimit;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TEnumAsByte<EAxis::Type> MeshUpAxis;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bDebug;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bNeedRestrictOnGround;
};
