// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AN_AkEvent` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "MarvelAnimNotify.h"
#include "MarvelRivalsExternalStubsTypes.h"
#include "MarvelTypes.h"
#include "UObject/SoftObjectPtr.h"
#include "AN_AkEvent.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AN_AkEvent"))
class MARVEL_API UAN_AkEvent : public UMarvelAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName AttachName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UAkAudioEvent> Event;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bReplay;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bEndWithAbility;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bEndWithMontage;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EAkFadeInterpolation FadeoutType;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float FadeoutTime;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bTargetSelf;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bTargetTeammate;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bTargetEnemy;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bUpdateLocationBeforePlay;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bSetSwitch;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SwitchGroup;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SwitchState;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EMarvelAudioType AudioType;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bCustomSocket;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bEnableCombo;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FAbilityAudioIdComboParam ComboParams;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTagContainer ActiveTags;
};
