// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AN_AkEventWorld` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "MarvelAnimNotify.h"
#include "MarvelRivalsExternalStubsTypes.h"
#include "UObject/ObjectPtr.h"
#include "AN_AkEventWorld.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AN_AkEventWorld"))
class MARVEL_API UAN_AkEventWorld : public UMarvelAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName AttachSocket;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UAkAudioEvent> Event;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FString EventName;
};
