// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AN_AkEventBreath` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AN_AkEvent.h"
#include "MarvelTypes.h"
#include "AN_AkEventBreath.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AN_AkEventBreath"))
class MARVEL_API UAN_AkEventBreath : public UAN_AkEvent
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EHeroBreathType BreathType;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EHeroBreathPriority Priority;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float CD;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float GlobalCD;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 TriggerThreshold;
};
