// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AN_HeroVoice` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "MarvelAnimNotify.h"
#include "MarvelTypes.h"
#include "AN_HeroVoice.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AN_HeroVoice"))
class MARVEL_API UAN_HeroVoice : public UMarvelAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EMarvelVoiceType VoiceType;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 AbilityID;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EAbilityVoiceStage Stage;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 VoiceID;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<int32> EmoteVoices;
};
