// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_SyncWithMT` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimMontage.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Components/SkeletalMeshComponent.h"
#include "MarvelTypes.h"
#include "UObject/ObjectPtr.h"
#include "AnimNotifyState_SyncWithMT.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_SyncWithMT"))
class MARVEL_API UAnimNotifyState_SyncWithMT : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UAnimMontage> LeaderMontage;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float SyncDiffThreshold;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float PositionMultiplier;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 SyncInterval;
	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TMap<TObjectPtr<USkeletalMeshComponent>,FSyncWithMTCacheInfo> SharedCachedData;
};
