// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_ReplaceOverlayMaterialInGame` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "MarvelTypes.h"
#include "NiagaraSystem.h"
#include "UObject/NoExportTypes.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotify_ReplaceOverlayMaterialInGame.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_ReplaceOverlayMaterialInGame"))
class MARVEL_API UAnimNotify_ReplaceOverlayMaterialInGame : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName ParamSwitchName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName ParamCaseName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UNiagaraSystem> NiagaraParticle;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector LocationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FRotator RotationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bDoNotUpdateRotation;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TMap<FName,float> FloatUserParameterValues;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bForceState;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EHeroSkinStateType ForceStateType;
};
