// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_TimedFXWithAO` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Components/MeshComponent.h"
#include "GameplayTagContainer.h"
#include "MarvelTypes.h"
#include "Particles/ParticleSystem.h"
#include "UObject/NoExportTypes.h"
#include "UObject/ObjectPtr.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotifyState_TimedFXWithAO.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedFXWithAO"))
class MARVEL_API UAnimNotifyState_TimedFXWithAO : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bBlockOnTagsOrActiveTags;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FGameplayTagContainer BlockTags;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FGameplayTagContainer ActiveTags;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UFXSystemAsset> FXSystemAsset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SpawnLocationSocket;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName AOReferenceSocket;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector2D UpDownFactor;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector2D LeftRightFactor;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bLeanCompensate;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bUpdateTransform;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bUpdateLocation;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bRenderCustomDepthPass : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bToBeTriggered;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bEnableFXSlomo;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float SlomoTimeScale;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	ENiagaraDeactivateTypeAtNotifyEnd NiagaraDeactivateTypeAtNotifyEnd;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FAnimNotifyFXParameterConfig ParameterConfig;
	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TMap<TObjectPtr<UMeshComponent>,FInstanceProgressInfo> ProgressInfoMap;

	virtual void NotifyBegin(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		float TotalDuration, const FAnimNotifyEventReference& EventReference) override;
	virtual void NotifyTick(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		float FrameDeltaTime, const FAnimNotifyEventReference& EventReference) override;
	virtual void NotifyEnd(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		const FAnimNotifyEventReference& EventReference) override;
};
