// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_TimedNiagaraEffectEx` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.
//
// FLATTENED. The game derives this from `UAnimNotifyState_TimedNiagaraEffect`, which stock UE
// marks MinimalAPI -- a subclass in another module fails at LINK time on its
// virtuals. So it derives from `UAnimNotifyState` here and declares that
// ancestor's properties directly. A .uasset tags each property by NAME, not by
// the class that declared it, so the bytes are identical either way -- and the
// ancestor's fields are read from the DUMP, which means you get the GAME's
// version of them, not the smaller stock one.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Engine/EngineTypes.h"
#include "GameplayTagContainer.h"
#include "MarvelTypes.h"
#include "NiagaraSystem.h"
#include "UObject/NoExportTypes.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotifyState_TimedNiagaraEffectEx.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedNiagaraEffectEx"))
class MARVEL_API UAnimNotifyState_TimedNiagaraEffectEx : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UNiagaraSystem> Template;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector LocationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FRotator RotationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector Scale3D;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bDestroyAtEnd;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float ComponentTimeScale;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FName> ComponentTags;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUsedTranslucencySortPriority : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 TranslucencySortPriority;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUsedTranslucencySortDistanceOffset : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float TranslucencySortDistanceOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bDoNotUpdateRotation : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bDoNotUpdateScale : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bCastShadow : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bRenderCustomDepthPass : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUsedCustomStencil : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 CustomStencilValue;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FLightingChannels LightingChannels;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TMap<FName,float> FloatUserParameterValues;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TMap<FName,FVector> VectorUserParameterValues;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TMap<FName,FLinearColor> ColorUserParameterValues;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	ENotifyEffectViewSide NotifyViewSide;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bPreCullCheck;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FActorTagNiagaraOverride> ActorTagNiagaraOverrides;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTagQuery PlayTagQuery;

	virtual void NotifyBegin(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		float TotalDuration, const FAnimNotifyEventReference& EventReference) override;
	virtual void NotifyTick(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		float FrameDeltaTime, const FAnimNotifyEventReference& EventReference) override;
	virtual void NotifyEnd(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		const FAnimNotifyEventReference& EventReference) override;
};
