// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_CameraInterp_TagTrigger` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotifyState_CameraInterp.h"
#include "GameplayTagContainer.h"
#include "AnimNotifyState_CameraInterp_TagTrigger.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_CameraInterp_TagTrigger"))
class MARVEL_API UAnimNotifyState_CameraInterp_TagTrigger : public UAnimNotifyState_CameraInterp
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTagContainer TriggerTags;
};
