// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_PlayAnimWithMeshByName` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "Animation/AnimSequenceBase.h"
#include "UObject/ObjectPtr.h"
#include "AnimNotify_PlayAnimWithMeshByName.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_PlayAnimWithMeshByName"))
class MARVEL_API UAnimNotify_PlayAnimWithMeshByName : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FString TargetComponentName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UAnimSequenceBase> TargetAnimation;
};
