// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_TimedScope` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "MarvelAbilityTargetActor_Scope.h"
#include "MarvelTypes.h"
#include "UObject/NoExportTypes.h"
#include "UObject/ObjectPtr.h"
#include "AnimNotifyState_TimedScope.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedScope"))
class MARVEL_API UAnimNotifyState_TimedScope : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bUseCustomSocket;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bUseAnimationSocket;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 ScopeId;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bOverrideLocation;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EMarvelScopeQuoteType InitLocationType;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector InitLocationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FRotator InitRotationOffset;
	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TObjectPtr<AMarvelAbilityTargetActor_Scope> ScopeActor;
};
