// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_HideMaterial` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "MarvelTypes.h"
#include "AnimNotify_HideMaterial.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_HideMaterial"))
class MARVEL_API UAnimNotify_HideMaterial : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FMaterialQuery> HideMaterialQueries;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FMaterialQuery> ShowMaterialQueries;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<int32> HideMaterialIDArray;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<int32> ShowMaterialIDArray;

	virtual void Notify(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		const FAnimNotifyEventReference& EventReference) override;
};
