// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_TimedWeaponEventBase` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "GameplayTagContainer.h"
#include "AnimNotifyState_TimedWeaponEventBase.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedWeaponEventBase"))
class MARVEL_API UAnimNotifyState_TimedWeaponEventBase : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUseModeEvent : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 EquipID;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bIsEndEquipIDConsistentWithBegin;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 WeaponModeIndex;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTag WeaponEventBeginTag;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTag WeaponEventEndTag;
};
