// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_PlayDecal` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "Kismet/KismetSystemLibrary.h"
#include "MarvelTypes.h"
#include "Materials/MaterialInterface.h"
#include "UObject/NoExportTypes.h"
#include "UObject/ObjectPtr.h"
#include "AnimNotify_PlayDecal.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_PlayDecal"))
class MARVEL_API UAnimNotify_PlayDecal : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bReplicated;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TObjectPtr<UMaterialInterface> DecalMaterial;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool Attached;
	UPROPERTY(EditAnywhere, Category = "Notify")
	ECommonPlayDir DecalDir;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float LineLength;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float DecalLifeTime;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float DecalFadeOut;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FVector DecalSizeMin;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FVector DecalSizeMax;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bAddOwnerRotation;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float RandomRot_Min;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float RandomRot_Max;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TEnumAsByte<EDrawDebugTrace::Type> DrawTraceType;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector LocationOffset;
};
