// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_EnableAnimatedIK` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Animation/AnimTypes.h"
#include "UObject/NoExportTypes.h"
#include "AnimNotifyState_EnableAnimatedIK.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_EnableAnimatedIK"))
class MARVEL_API UAnimNotifyState_EnableAnimatedIK : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bAutoSampling : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName MachineName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName IKBoneName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName EffectorTargetName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TEnumAsByte<EBoneControlSpace> EffectorLocationSpace;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float NotifyDuration;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float NotifyBeginTime;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float SamplingInterval;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FVector> EffectorLocationSamples;
};
