// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_TimedChaosBatchParticleEffect` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "MarvelTypes.h"
#include "NiagaraSystem.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotifyState_TimedChaosBatchParticleEffect.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedChaosBatchParticleEffect"))
class MARVEL_API UAnimNotifyState_TimedChaosBatchParticleEffect : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UNiagaraSystem> Template;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName PreviewSocketName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FName> TargetSocketNames;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FChaosDesEffectParam> CombineEffectParams;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EChaosParticleAnimNotifyType ChaosParticleAnimNotifyType;
};
