// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_LerpCameraSpringArmLength` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Curves/CurveFloat.h"
#include "MarvelTypes.h"
#include "UObject/ObjectPtr.h"
#include "AnimNotifyState_LerpCameraSpringArmLength.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_LerpCameraSpringArmLength"))
class MARVEL_API UAnimNotifyState_LerpCameraSpringArmLength : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SpringArmComponentName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bUseCurrentArmLengthAsFrom;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float FromArmLength;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	ELerpCameraSpringArmLengthTargetMode TargetMode;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float ToArmLength;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float BodySizeChangeTargetArmLengthMultiplier;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 BodySizeChangeBuffId;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FLerpCameraSpringArmLengthBodySizeStageCameraExternalScales BodySizeChangeStageCameraExternalScales;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UCurveFloat> ProgressCurve;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bHoldArmLengthUntilMontageEnd;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bRestoreArmLengthOnRelease;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bForceSpringArmUpdate;
};
