// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_PlayNiagaraEffectEx` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.
//
// FLATTENED. The game derives this from `UAnimNotify_PlayNiagaraEffect`, which stock UE
// marks MinimalAPI -- a subclass in another module fails at LINK time on its
// virtuals. So it derives from `UAnimNotify` here and declares that
// ancestor's properties directly. A .uasset tags each property by NAME, not by
// the class that declared it, so the bytes are identical either way -- and the
// ancestor's fields are read from the DUMP, which means you get the GAME's
// version of them, not the smaller stock one.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "Engine/EngineTypes.h"
#include "GameplayTagContainer.h"
#include "MarvelTypes.h"
#include "NiagaraSystem.h"
#include "UObject/NoExportTypes.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotify_PlayNiagaraEffectEx.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_PlayNiagaraEffectEx"))
class MARVEL_API UAnimNotify_PlayNiagaraEffectEx : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UNiagaraSystem> Template;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bUseCombineEffect;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UNiagaraSystem> TemplateCombineEffect;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector LocationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FRotator RotationOffset;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FVector Scale;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bAbsoluteScale;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bDeactivateOnMontageEnded;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 Attached : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float EffectLastTime;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float ComponentTimeScale;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TMap<FName,float> FloatUserParameterValues;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TMap<FName,FVector> VectorUserParameterValues;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TMap<FName,FLinearColor> ColorUserParameterValues;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUsedCustomStencil : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 CustomStencilValue;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUsedTranslucencySortPriority : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 TranslucencySortPriority;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUsedTranslucencySortDistanceOffset : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float TranslucencySortDistanceOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bCastShadow : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bRenderCustomDepthPass : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bDoNotUpdateRotation : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUpdateRotationByVelocity : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bAutoPossessAttachment : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	ETriggerFXType CombineFXType;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FName> NiagaraTags;
	UPROPERTY(EditAnywhere, Category = "Notify")
	uint8 bBlockOnTagsOrActiveTags : 1;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FGameplayTagContainer BlockTags;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FGameplayTagContainer ActiveTags;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bOwnerNoSee : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bOnlyOwnerSee : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bClientIsPlayerViewSelfNoSee : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bOnlyClientIsPlayerViewSelfSee : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bEnableFXSlomo;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float SlomoTimeScale;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FLightingChannels LightingChannels;

	/** Defaults the GAME inherits from UAnimNotify_PlayNiagaraEffect, whose constructor this
	 * class no longer runs because it was flattened away. Without these the stub's
	 * CDO disagrees with the game's, which both mis-previews and makes the affected
	 * properties impossible to author (Unreal omits values equal to the default). */
	UAnimNotify_PlayNiagaraEffectEx()
	{
		Attached = true;
		Scale = FVector(1.0f);
		bAbsoluteScale = false;
	}

	virtual void Notify(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		const FAnimNotifyEventReference& EventReference) override;
};
