// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_Cue` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "GameplayTagContainer.h"
#include "MarvelTypes.h"
#include "AnimNotify_Cue.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_Cue"))
class MARVEL_API UAnimNotify_Cue : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Notify")
	FGameplayTag GameplayCueTag;
	UPROPERTY(EditAnywhere, Category = "Notify")
	EAnimNotifyCueEvent EventType;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FString Note;
};
