// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_SetAllBodiesBelowSimulatePhysics` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "MarvelTypes.h"
#include "AnimNotifyState_SetAllBodiesBelowSimulatePhysics.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_SetAllBodiesBelowSimulatePhysics"))
class MARVEL_API UAnimNotifyState_SetAllBodiesBelowSimulatePhysics : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FANS_SetAllBodiesBelowSimulatePhysics_BoneName> BoneNames;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bSimulatePhysics;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bIncludeSelf;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bReverseWhenEnd;
};
