// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_PsylockeSwimControl` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "AnimNotifyState_PsylockeSwimControl.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_PsylockeSwimControl"))
class MARVEL_API UAnimNotifyState_PsylockeSwimControl : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName IdleSectionName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SwimSectionName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float SlowSwimThreshold;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float SlowSwimAnimRate;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float FastSwimAnimRate;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float MaxSpeed;
};
