// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_ApplyDash_WithFilter` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotify_ApplyDash.h"
#include "GameplayEffectTypes.h"
#include "GameplayTagContainer.h"
#include "AnimNotify_ApplyDash_WithFilter.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_ApplyDash_WithFilter"))
class MARVEL_API UAnimNotify_ApplyDash_WithFilter : public UAnimNotify_ApplyDash
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTagRequirements TagTagRequirements;
};
