// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_TimedWeaponAnim` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Animation/AnimSequenceBase.h"
#include "MarvelTypes.h"
#include "UObject/ObjectPtr.h"
#include "AnimNotifyState_TimedWeaponAnim.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedWeaponAnim"))
class MARVEL_API UAnimNotifyState_TimedWeaponAnim : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 EquipID;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bIsEndEquipIDConsistentWithBegin;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EWeaponMeshType MeshType;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UAnimSequenceBase> WeaponAnimation;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float PlayRate;
};
