// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_PlayWeaponMaterial` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "AnimNotify_PlayWeaponMaterial.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_PlayWeaponMaterial"))
class MARVEL_API UAnimNotify_PlayWeaponMaterial : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool ShowOrHideWeapon;
	UPROPERTY(EditAnywhere, Category = "Notify")
	int32 EquipID;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName ParamerName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float EndValue;
};
