// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_TimedSkeletonAnimation` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Animation/AnimationAsset.h"
#include "Components/SkeletalMeshComponent.h"
#include "Components/SkinnedMeshComponent.h"
#include "Engine/EngineTypes.h"
#include "Engine/SkeletalMesh.h"
#include "GameFramework/Actor.h"
#include "GameplayTagContainer.h"
#include "MarvelTypes.h"
#include "Materials/MaterialInterface.h"
#include "UObject/NoExportTypes.h"
#include "UObject/ObjectPtr.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotifyState_TimedSkeletonAnimation.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedSkeletonAnimation"))
class MARVEL_API UAnimNotifyState_TimedSkeletonAnimation : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	ETimedSkeletonAnimationMeshSource MeshSource;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<USkeletalMesh> SkeletalMeshTemplate;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<TSoftObjectPtr<UMaterialInterface>> OverrideMaterials;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 UseWeaponMeshSkeletaMesh;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName WeaponMeshName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName TargetComponentTag;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FName> AddComponentTags;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FName> CommonEffectExcludedSlotSuffixes;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FMaterialTag> CommonEffectExcludedSlotTags;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FVector LocationOffset;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FRotator RotationOffset;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TMap<FName,FVector> ChildBoneScales;
	UPROPERTY(EditAnywhere, Category = "Notify")
	uint8 bDoNotAttach : 1;
	UPROPERTY(EditAnywhere, Category = "Notify")
	uint8 bDoNotUpdateLocation : 1;
	UPROPERTY(EditAnywhere, Category = "Notify")
	uint8 bDoNotUpdateRotation : 1;
	UPROPERTY(EditAnywhere, Category = "Notify")
	uint8 bDoNotUpdateScale : 1;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bVisibleDuringAnimNotifyState;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bFixVisibleDuringAnimNotifyState;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bDelayHiddenOnPaused;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float DelayHiddenCheckTime;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bIsRenderCustomDepth;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUsedCustomStencil : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 CustomStencilValue;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bReceiveDecal;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bBeachFootPrint;
	UPROPERTY(EditAnywhere, Category = "Notify")
	EVisibilityBasedAnimTickOption VisibilityBasedAnimTickOption;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bDoNotTickWhenInvisibleOrHiddenInGame;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bDoNotTickOnServer;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bSimulatePhysics;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bUsePhysicsActorPreset;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bSetTeamVisualOnMaterials;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UAnimationAsset> AnimToPlay;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bIsLoop;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bSyncAnimPosFromNotify;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bSyncMontageSection;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float AnimStartPos;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bSyncMontageV2;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bNotReduceDetalTimeForChildMesh;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bNotReplayInBlendOut;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float MinPosDiffForJumpSectionAfterParentStop;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bSkeletalUseAttachParentBound;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bCustomLightingChannels;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FLightingChannels LightingChannels;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FGameplayTagQuery EnableTagQuery;
	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TObjectPtr<USkeletalMeshComponent> DelayHandleSkeletaMesh;
	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TObjectPtr<AActor> OwnerMeshActor;
	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TMap<TObjectPtr<AActor>,TObjectPtr<USkeletalMeshComponent>> CachedDelayHandleSkeletalMeshMap;

	virtual void NotifyBegin(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		float TotalDuration, const FAnimNotifyEventReference& EventReference) override;
	virtual void NotifyTick(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		float FrameDeltaTime, const FAnimNotifyEventReference& EventReference) override;
	virtual void NotifyEnd(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		const FAnimNotifyEventReference& EventReference) override;
};
