// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_PlayFXOnGroundWithAO` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "Particles/ParticleSystem.h"
#include "UObject/NoExportTypes.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotify_PlayFXOnGroundWithAO.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_PlayFXOnGroundWithAO"))
class MARVEL_API UAnimNotify_PlayFXOnGroundWithAO : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bCastShadow : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bRenderCustomDepthPass : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bGroundTraceDestructible : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UFXSystemAsset> FXSystemAsset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName BoneName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FTransform BoneSpaceOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float GroundTraceStartZ;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float GroundTraceEndZ;
};
