// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_PresetDestruction` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "GameFramework/DamageType.h"
#include "Templates/SubclassOf.h"
#include "AnimNotify_PresetDestruction.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_PresetDestruction"))
class MARVEL_API UAnimNotify_PresetDestruction : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bCreateSummonerWithEff;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName SpawnSocketName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TArray<int32> SummonerIDs;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bStopJudgeDamage;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bApplyBuffSpec;
	UPROPERTY(EditAnywhere, Category = "Notify")
	int32 BuffSpecId;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float Damage;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bApplyDestructibleDamage;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float DestructibleDamage;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float DestructibleRadius;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float DestructibleImpluse;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TSubclassOf<UDamageType> DestructibleDamageType;
};
