// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_UpdateMaterial` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Curves/CurveFloat.h"
#include "MarvelTypes.h"
#include "UObject/ObjectPtr.h"
#include "AnimNotifyState_UpdateMaterial.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_UpdateMaterial"))
class MARVEL_API UAnimNotifyState_UpdateMaterial : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName MachineName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName StateName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TArray<FAnimationMaterialCurveParam> SingleMaterialCurve;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName ParameterName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TObjectPtr<UCurveFloat> Curve;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bRecoverToCustomValue;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float CustomValue;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bRecoverDefaultValue;

	virtual void NotifyBegin(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		float TotalDuration, const FAnimNotifyEventReference& EventReference) override;
	virtual void NotifyTick(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		float FrameDeltaTime, const FAnimNotifyEventReference& EventReference) override;
	virtual void NotifyEnd(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		const FAnimNotifyEventReference& EventReference) override;
};
