// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_PlayFXWithAO` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "Components/SkeletalMeshComponent.h"
#include "MarvelTypes.h"
#include "NiagaraSystem.h"
#include "Particles/ParticleSystem.h"
#include "UObject/NoExportTypes.h"
#include "UObject/ObjectPtr.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotify_PlayFXWithAO.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_PlayFXWithAO"))
class MARVEL_API UAnimNotify_PlayFXWithAO : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName BoneName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bIsAttached;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bUseBoneLocationOnly;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bDoNotUpdateRotation;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FTransform OffsetTransform;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UNiagaraSystem> NiagaraParticle;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UParticleSystem> CascadeParticle;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float MaxPitch;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float MinPitch;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bUseLerpWithAO;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bUsePitchAOOnly;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector LerpStart;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector LerpEnd;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bRenderCustomDepthPass : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float EffectLastTime;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bEnableFXSlomo;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float SlomoTimeScale;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float LoadAssetTimeout;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FAnimNotifyFXParameterConfig ParameterConfig;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<USkeletalMeshComponent> OwnerMeshComp;

	virtual void Notify(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		const FAnimNotifyEventReference& EventReference) override;
};
