// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_LerpBoneTransform` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Curves/CurveFloat.h"
#include "UObject/NoExportTypes.h"
#include "UObject/ObjectPtr.h"
#include "AnimNotifyState_LerpBoneTransform.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_LerpBoneTransform"))
class MARVEL_API UAnimNotifyState_LerpBoneTransform : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName BoneName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bApplyAnimDrivenBoneTransform;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FTransform FromTransform;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FTransform ToTransform;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UCurveFloat> ProgressCurve;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bComposeActiveFluxKinematicBuoyancyOnRoot;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bCompensateMeshRelativeLocationOnRoot;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bCompensateSwimmingCapsuleFloatHeightOnRoot;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float SwimmingCapsuleFloatSubmergeDepth;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bApplyAbsoluteTransformToPhysicsRoot;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bDisablePhysicsOnRootBody;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bHoldRootPhysicsUntilMontageEnd;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bZeroRootPhysicsBodyVelocity;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bWakeRootPhysicsBody;
};
