// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_TimedNiagaraEffectEx_Skelot` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotifyState_TimedNiagaraEffectEx.h"
#include "InstancedStruct.h"
#include "NiagaraSystem.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotifyState_TimedNiagaraEffectEx_Skelot.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedNiagaraEffectEx_Skelot"))
class MARVEL_API UAnimNotifyState_TimedNiagaraEffectEx_Skelot : public UAnimNotifyState_TimedNiagaraEffectEx
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bApplySkelotScale;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bCombineFX;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UNiagaraSystem> CombineTemplateAsset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 VectorParamNum;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 FloatParamNum;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 IntParamNum;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TArray<FInstancedStruct> IntParamOps;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TArray<FInstancedStruct> FloatParamOps;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TArray<FInstancedStruct> VectorParamOps;
};
