// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_TagNotify` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.
//
// FLATTENED. The game derives this from `UAnimNotify_PlayMontageNotify`, which stock UE
// marks MinimalAPI -- a subclass in another module fails at LINK time on its
// virtuals. So it derives from `UAnimNotify` here and declares that
// ancestor's properties directly. A .uasset tags each property by NAME, not by
// the class that declared it, so the bytes are identical either way -- and the
// ancestor's fields are read from the DUMP, which means you get the GAME's
// version of them, not the smaller stock one.

#pragma once

#include "CoreMinimal.h"
#include "Abilities/GameplayAbilityTypes.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "GameplayTagContainer.h"
#include "AnimNotify_TagNotify.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_TagNotify"))
class MARVEL_API UAnimNotify_TagNotify : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName NotifyName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTag EventTag;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayEventData Payload;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bHasBlueprintReceivedNotify : 1;
};
