// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_TimedParticleOnWeapon` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.
//
// FLATTENED. The game derives this from `UAnimNotifyState_TimedParticleEffect`, which stock UE
// marks MinimalAPI -- a subclass in another module fails at LINK time on its
// virtuals. So it derives from `UAnimNotifyState` here and declares that
// ancestor's properties directly. A .uasset tags each property by NAME, not by
// the class that declared it, so the bytes are identical either way -- and the
// ancestor's fields are read from the DUMP, which means you get the GAME's
// version of them, not the smaller stock one.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "GameplayTagContainer.h"
#include "Particles/ParticleSystem.h"
#include "UObject/NoExportTypes.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotifyState_TimedParticleOnWeapon.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedParticleOnWeapon"))
class MARVEL_API UAnimNotifyState_TimedParticleOnWeapon : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Notify")
	TSoftObjectPtr<UParticleSystem> PSTemplate;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FVector LocationOffset;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FRotator RotationOffset;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bDestroyAtEnd;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUseExisting : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bAttached : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 EquipID;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTag PSComponentTag;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector Scale;

	virtual void NotifyBegin(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		float TotalDuration, const FAnimNotifyEventReference& EventReference) override;
	virtual void NotifyTick(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		float FrameDeltaTime, const FAnimNotifyEventReference& EventReference) override;
	virtual void NotifyEnd(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		const FAnimNotifyEventReference& EventReference) override;
};
