// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_SpawnScope` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotify_SocketBase.h"
#include "MarvelTypes.h"
#include "UObject/NoExportTypes.h"
#include "AnimNotify_SpawnScope.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_SpawnScope"))
class MARVEL_API UAnimNotify_SpawnScope : public UAnimNotify_SocketBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 ScopeId;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bOverrideLocation;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EMarvelScopeQuoteType InitLocationType;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector InitLocationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FRotator InitRotationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bShouldPredict;
};
