// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_CameraInterp` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "CameraInterp.h"
#include "GameFramework/Actor.h"
#include "GameplayTagContainer.h"
#include "MarvelTypes.h"
#include "UObject/ObjectPtr.h"
#include "AnimNotifyState_CameraInterp.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_CameraInterp"))
class MARVEL_API UAnimNotifyState_CameraInterp : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool IsLocal;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTagContainer IgnoreTags;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTagContainer IgnoreTagsWhenEnd;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UCameraInterp> CameraInterpAsset;
	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TMap<TObjectPtr<AActor>,FSpringArmControlHandler> SpringArmHandlers;
};
