// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotify_PlayParticleByTag` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.
//
// FLATTENED. The game derives this from `UAnimNotify_PlayParticleEffect`, which stock UE
// marks MinimalAPI -- a subclass in another module fails at LINK time on its
// virtuals. So it derives from `UAnimNotify` here and declares that
// ancestor's properties directly. A .uasset tags each property by NAME, not by
// the class that declared it, so the bytes are identical either way -- and the
// ancestor's fields are read from the DUMP, which means you get the GAME's
// version of them, not the smaller stock one.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "GameplayTagContainer.h"
#include "Particles/ParticleSystem.h"
#include "UObject/NoExportTypes.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotify_PlayParticleByTag.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_PlayParticleByTag"))
class MARVEL_API UAnimNotify_PlayParticleByTag : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UParticleSystem> PSTemplate;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector LocationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FRotator RotationOffset;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FVector Scale;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 Attached : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UParticleSystem> DefaultPSTemplate;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTag Tag;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UParticleSystem> TagPSTemplate;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bCastShadow : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bRenderCustomDepthPass : 1;

	/** Defaults the GAME inherits from UAnimNotify_PlayParticleEffect, whose constructor this
	 * class no longer runs because it was flattened away. Without these the stub's
	 * CDO disagrees with the game's, which both mis-previews and makes the affected
	 * properties impossible to author (Unreal omits values equal to the default). */
	UAnimNotify_PlayParticleByTag()
	{
		Attached = true;
		Scale = FVector(1.0f);
	}

	virtual void Notify(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
		const FAnimNotifyEventReference& EventReference) override;
};
