// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_UpdateAccessoryMaterial` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "MarvelTypes.h"
#include "AnimNotifyState_UpdateAccessoryMaterial.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_UpdateAccessoryMaterial"))
class MARVEL_API UAnimNotifyState_UpdateAccessoryMaterial : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName MachineName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName StateName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FName> ComponentTags;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName ComponentName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bMatchComponentTagsOnParents;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FAccessoryMaterialCurveParam> MaterialCurves;
};
