// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.AnimNotifyState_TimedStaticMeshVAT` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Engine/EngineTypes.h"
#include "Engine/StaticMesh.h"
#include "Materials/MaterialInterface.h"
#include "UObject/NoExportTypes.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotifyState_TimedStaticMeshVAT.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedStaticMeshVAT"))
class MARVEL_API UAnimNotifyState_TimedStaticMeshVAT : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UStaticMesh> StaticMeshTemplate;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<TSoftObjectPtr<UMaterialInterface>> OverrideMaterials;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TMap<FName,FName> VAT_MaterialParamCurveMappingInfo;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FVector LocationOffset;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FRotator RotationOffset;
	UPROPERTY(EditAnywhere, Category = "Notify")
	uint8 bDoNotAttach : 1;
	UPROPERTY(EditAnywhere, Category = "Notify")
	uint8 bDoNotUpdateLocation : 1;
	UPROPERTY(EditAnywhere, Category = "Notify")
	uint8 bDoNotUpdateRotation : 1;
	UPROPERTY(EditAnywhere, Category = "Notify")
	uint8 bDoNotUpdateScale : 1;
	UPROPERTY(EditAnywhere, Category = "Notify")
	uint8 bReceivesDecals : 1;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bIsRenderCustomDepth;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bUseAttachParentBound;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bCustomLightingChannels;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FLightingChannels LightingChannels;
};
