// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.ANS_AkEvent` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "MarvelRivalsExternalStubsTypes.h"
#include "UObject/SoftObjectPtr.h"
#include "ANS_AkEvent.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "ANS_AkEvent"))
class MARVEL_API UANS_AkEvent : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName AttachName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName GameAttachName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UAkAudioEvent> Event;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bReplay;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	EAkFadeInterpolation FadeoutType;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float FadeoutTime;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bTargetSelf;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bTargetTeammate;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bTargetEnemy;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bCustomSocket;
};
