// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.CameraInterp` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.
//
// FIELD-LESS BY DESIGN: this type is only ever referenced through a pointer,
// which serialises an object path. The name is what has to be right.

#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "CameraInterp.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "CameraInterp"))
class MARVEL_API UCameraInterp : public UObject
{
	GENERATED_BODY()

public:
	// No serialised properties.
};
