// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.MarvelTagNotify_ChangeSkinParam` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotify_MontageTagNotify.h"
#include "MarvelTagNotify_ChangeSkinParam.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "MarvelTagNotify_ChangeSkinParam"))
class MARVEL_API UMarvelTagNotify_ChangeSkinParam : public UAnimNotify_MontageTagNotify
{
	GENERATED_BODY()

public:
	// No serialised properties.
};
