// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Marvel.MarvelTypes` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimInstance.h"
#include "Components/SkeletalMeshComponent.h"
#include "Curves/CurveBase.h"
#include "Curves/CurveFloat.h"
#include "Curves/CurveVector.h"
#include "Engine/EngineTypes.h"
#include "GameFramework/Actor.h"
#include "GameplayTagContainer.h"
#include "Materials/MaterialInterface.h"
#include "NiagaraSystem.h"
#include "Particles/ParticleSystemComponent.h"
#include "UObject/NoExportTypes.h"
#include "UObject/ObjectPtr.h"
#include "UObject/SoftObjectPtr.h"
#include "MarvelTypes.generated.h"

UENUM(BlueprintType)
enum class EAbilityVoiceStage : uint8
{
	Activate = 0,
	Missile = 1,
	End = 2,
	Break = 3,
	Commit = 4,
	Custom0 = 5,
	Custom1 = 6,
	Custom2 = 7,
	Projectile = 8,
	Scope = 9,
	Summoned = 10,
	Undefined = 16,
	EAbilityVoiceStage_MAX = 17,
};

UENUM(BlueprintType)
enum class EAmmoClipType : uint8
{
	NONE = 0,
	Ammo1 = 3,
	Ammo2 = 28,
	Ammo3 = 30,
	SkillEnergy = 22,
	SkillEnergy2 = 24,
	SkillEnergy3 = 26,
	SkillEnergy4 = 36,
	Energy = 20,
	SpecialEnergy = 32,
	EAmmoClipType_MAX = 37,
};

UENUM(BlueprintType)
enum class EAnimNotifyCueEvent : uint8
{
	Add = 0,
	Remove = 1,
	Execute = 2,
	EAnimNotifyCueEvent_MAX = 3,
};

UENUM(BlueprintType)
enum class EChaosDesEffectParamType : uint8
{
	Actor = 0,
	Bool = 1,
	Int = 2,
	Float = 3,
	Color = 4,
	FVector = 5,
	EChaosDesEffectParamType_MAX = 6,
};

UENUM(BlueprintType)
enum class EChaosFieldType : uint8
{
	Ammo = 0,
	Projectile = 1,
	Scope = 2,
	EChaosFieldType_MAX = 3,
};

UENUM(BlueprintType)
enum class EChaosParticleAnimNotifyType : uint8
{
	None = 0,
	PlayNiagaraEffect = 1,
	PlaySound = 2,
	TimedBatchParticleEffect = 3,
	EChaosParticleAnimNotifyType_MAX = 4,
};

UENUM(BlueprintType)
enum class ECommonPlayDir : uint8
{
	UP = 0,
	DOWN = 1,
	FOWARD = 2,
	BACK = 3,
	LEFT = 4,
	RIGHT = 5,
	CAMERA = 6,
	AIM = 7,
	CUSTOM = 8,
	ECommonPlayDir_MAX = 9,
};

UENUM(BlueprintType)
enum class EDashDirectionType : uint8
{
	CrossHair = 0,
	CustomDirection = 1,
	DefaultDirection = 2,
	TargetLocation = 3,
	TargetActor = 4,
	TargetLocationInterp = 5,
	TargetActorInterp = 6,
	InputDirection = 7,
	EDashDirectionType_MAX = 8,
};

UENUM(BlueprintType)
enum class EDashFinishVelocityMode : uint8
{
	Zeroing = 0,
	MaintainLastVelocity = 1,
	MaintainEndFrameVelocity = 2,
	EDashFinishVelocityMode_MAX = 3,
};

UENUM(BlueprintType)
enum class EHeroBreathPriority : uint8
{
	Highest = 0,
	High = 1,
	Middle = 2,
	Low = 3,
	Lowest = 4,
	EHeroBreathPriority_MAX = 5,
};

UENUM(BlueprintType)
enum class EHeroBreathType : uint8
{
	None = 0,
	D_NORMAL_ATTACK = 1,
	D_SPECIAL_DAMAGE = 2,
	D_TAKE_NORMAL_DAMAGE = 3,
	D_TAKE_CRITICAL_DAMAGE = 4,
	D_TAKE_PUSHED = 5,
	D_BASE_MOVE = 6,
	D_BASE_JUMP_NONCONTINUOUS = 7,
	D_ACC_FLY = 8,
	D_SP_MOVE = 9,
	D_BIG_JUMP = 10,
	D_DOUBLE_JUMP = 11,
	D_BIG_JUMP_LAND = 12,
	D_HIGH_SPACE_LAND = 13,
	D_RUN = 14,
	D_RUN_END = 15,
	D_RUN_RESTART = 16,
	D_DEATH = 17,
	EHeroBreathType_MAX = 18,
};

UENUM(BlueprintType)
enum class EHeroSkinStateType : uint8
{
	Normal = 0,
	EmoteColor = 1,
	EHeroSkinStateType_MAX = 2,
};

UENUM(BlueprintType)
enum class EHideWeapon : uint8
{
	All = 0,
	WeaponMesh = 1,
	SecondWeaponMesh = 2,
	EHideWeapon_MAX = 3,
};

UENUM(BlueprintType)
enum class ELerpCameraSpringArmLengthTargetMode : uint8
{
	AbsoluteArmLength = 0,
	BodySizeChangeBaseMultiplier = 1,
	ELerpCameraSpringArmLengthTargetMode_MAX = 2,
};

UENUM(BlueprintType)
enum class EMarvelAbilityUIHudAnim : uint8
{
	Jump = 0,
	DoubleJump = 1,
	Melee = 2,
	Sprint = 3,
	EMarvelAbilityUIHudAnim_MAX = 4,
};

UENUM(BlueprintType)
enum class EMarvelAudioType : uint8
{
	MAT_None = 0,
	MAT_Foley = 1,
	MAT_Ability = 2,
	MAT_Weapon = 3,
	MAT_Impact = 4,
	MAT_Breath = 5,
	MAT_HeroVocal = 6,
	MAT_SystemVocal = 7,
	MAT_Music = 8,
	MAT_UI = 9,
	MAT_Ambience = 10,
	MAT_Broken = 11,
	MAT_Modes = 12,
	MAT_Hit = 13,
	MAT_Critical = 14,
	MAT_Max = 15,
	MAT_MAX = 16,
};

UENUM(BlueprintType)
enum class EMarvelPawnBodyType : uint8
{
	Center = 0,
	Left = 1,
	Right = 2,
	Head = 3,
	Custom = 4,
	EMarvelPawnBodyType_MAX = 5,
};

UENUM(BlueprintType)
enum class EMarvelScopeQuoteType : uint8
{
	None = 0,
	AttachedInstigator = 1,
	AttachedOwner = 2,
	AttachedQuote = 3,
	QuoteTransform = 4,
	InstigatorCenter = 5,
	InstigatorLeftHand = 6,
	InstigatorRightHand = 7,
	InstigatorHead = 8,
	CustomTransform = 9,
	EMarvelScopeQuoteType_MAX = 10,
};

UENUM(BlueprintType)
enum class EMarvelVoiceType : uint8
{
	SystemVoice = 0,
	HeroVoice = 1,
	LevelVoice = 2,
	EMarvelVoiceType_MAX = 3,
};

UENUM()
enum class EMaterialParameterValueSource : uint32
{
	RangeValues = 0,
	ExternalCurve = 1,
	AnimationCurve = 2,
	EMaterialParameterValueSource_MAX = 3,
};

UENUM(BlueprintType)
enum class EMaterialQueryType : uint8
{
	QueryBySlotIndex = 0,
	QueryBySlotName = 1,
	QueryBySlotTag = 2,
	EMaterialQueryType_MAX = 3,
};

UENUM(BlueprintType)
enum class EMontageType : uint8
{
	NoUpperBody = 0,
	UppderBodyWhenMoving = 1,
	AlwaysUpperBody = 2,
	UpperBodyWhenMovingButFullBodyTurnInPlace = 3,
	CustomUpperBody = 4,
	EMontageType_MAX = 5,
};

UENUM(BlueprintType)
enum class EMovementStance : uint8
{
	MOVEMENTSTANCE_Default = 0,
	MOVEMENTSTANCE_Left = 1,
	MOVEMENTSTANCE_Right = 2,
	MOVEMENTSTANCE_MAX = 3,
};

UENUM(BlueprintType)
enum class ENiagaraDeactivateTypeAtNotifyEnd : uint8
{
	DeactivateImmediate = 0,
	Deactivate = 1,
	Ignore = 2,
	ENiagaraDeactivateTypeAtNotifyEnd_MAX = 3,
};

UENUM(BlueprintType)
enum class ENotifyEffectViewSide : uint8
{
	All = 0,
	SelfSide = 1,
	Other = 2,
	ENotifyEffectViewSide_MAX = 3,
};

UENUM(BlueprintType)
enum class EPlayEffectViewSide : uint8
{
	DontPlay = 0,
	ViewTarget = 1,
	NoViewTarget = 2,
	Both = 0 UMETA(Hidden),
	EPlayEffectViewSide_MAX = 3,
};

UENUM(BlueprintType)
enum class ERefreshCooldownType : uint8
{
	Reset = 0,
	ERefreshCooldownType_MAX = 1,
};

UENUM()
enum class ESkinState : uint32
{
	Unknown = 0,
	PingA = 1,
	PingB = 2,
	ESkinState_MAX = 3,
};

UENUM(BlueprintType)
enum class ETimedAttachment : uint8
{
	ETA_None = 0,
	ETA_AttachToComponent = 1,
	ETA_MAX = 2,
};

UENUM(BlueprintType)
enum class ETimedSkeletonAnimationMeshSource : uint8
{
	SkeletalMeshTemplate = 0,
	CurrentChildBPMainMesh = 1,
	ExistingTaggedMesh = 2,
	ETimedSkeletonAnimationMeshSource_MAX = 3,
};

UENUM(BlueprintType)
enum class ETimedVisibility : uint8
{
	ETV_None = 0,
	ETV_SetVisibilityOn = 1,
	ETV_SetVisibilityOff = 2,
	ETV_SetHiddenInGameOn = 3,
	ETV_SetHiddenInGameOff = 4,
	ETV_MAX = 5,
};

UENUM(BlueprintType)
enum class ETriggerFXType : uint8
{
	Fire = 0,
	Hit = 1,
	Trajectory = 2,
	Projectile = 3,
	DynamicBeam = 4,
	ETriggerFXType_MAX = 5,
};

UENUM(BlueprintType)
enum class EWaitForTagsToStopMode : uint8
{
	StopTimeline = 0,
	StopMontageOnly = 1,
	EWaitForTagsToStopMode_MAX = 2,
};

UENUM(BlueprintType)
enum class EWeaponMeshType : uint8
{
	NoneMesh = 0,
	CharacterMesh = 1,
	WeaponMesh = 2,
	WeaponMesh2 = 3,
	EWeaponMeshType_MAX = 4,
};

USTRUCT(BlueprintType)
struct FANS_SetAllBodiesBelowSimulatePhysics_BoneName
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName BoneName;
};

USTRUCT(BlueprintType)
struct FAbilityAudioIdComboParam
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float ComboDuration = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<int32> ComboAudioID;
};

USTRUCT(BlueprintType)
struct FAccessoryMaterialCurveParam
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName ParameterName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UCurveBase> Curve;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bRecoverDefaultValue = false;
};

USTRUCT(BlueprintType)
struct FActorTagNiagaraOverride
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FName ActorTag;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<UNiagaraSystem> NiagaraSystem;
};

USTRUCT(BlueprintType)
struct FAnimNotifyFXParameterConfig
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bUseCustomParameters = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TMap<FName,bool> BoolUserParameterValues;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TMap<FName,float> FloatUserParameterValues;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TMap<FName,FVector> VectorUserParameterValues;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TMap<FName,FLinearColor> ColorUserParameterValues;
};

USTRUCT(BlueprintType)
struct FMaterialTag
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Notify")
	FName Tag;
};

USTRUCT(BlueprintType)
struct FMaterialQuery
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Notify")
	EMaterialQueryType QueryType = EMaterialQueryType::QueryBySlotIndex;
	UPROPERTY(EditAnywhere, Category = "Notify")
	int32 SlotIndex = 0;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName SlotName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FMaterialTag SlotTag;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bIndex2TagCompatibleCode = false;
};

USTRUCT(BlueprintType)
struct FAnimationMaterialCurveParam
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Notify")
	FName MeshName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	int32 MaterialSlot = 0;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FMaterialQuery MaterialQuery;
	UPROPERTY(EditAnywhere, Category = "Notify")
	FName ParameterName;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TObjectPtr<UCurveBase> Curve;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bRecoverToCustomValue = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float CustomValue = 0.f;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bRecoverDefaultValue = false;
};

USTRUCT(BlueprintType)
struct FChaosDesActorParam
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<AActor> Actor;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bUseActorPosition = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bUseNearlyPosition = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<UNiagaraSystem> ActorEndEffect;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float DelayTime = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bIsUseCombine = false;
};

USTRUCT(BlueprintType)
struct FChaosDesEffectParam
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FString ParamName;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	EChaosDesEffectParamType ParamType = EChaosDesEffectParamType::Actor;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FChaosDesActorParam ActorInfo;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool BoolParam = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	int32 IntParam = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float FloatParam = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FLinearColor ColorParam = FLinearColor(ForceInitToZero);
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FVector VectorParam = FVector::ZeroVector;
};

USTRUCT(BlueprintType)
struct FMarvelGameplayTagRequirements
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FGameplayTagContainer RequireTags;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FGameplayTagContainer IgnoreTags;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bUseTagQuery = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FGameplayTagQuery TagQuery;
};

USTRUCT(BlueprintType)
struct FDashAbilityInfo
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float DashDuration = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<UCurveFloat> SpeedCurve;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<UCurveFloat> DistanceCurve;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<UCurveVector> PathOffsetCurve;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<UCurveFloat> MoveFractionCurve;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<UCurveFloat> DistanceFallOff;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<UCurveFloat> TargetLerpSpeedHorizontal;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<UCurveFloat> TargetLerpSpeedVertical;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bRestrictSpeedToExpected = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float MaxSpeed = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float NoSmoothCorrectionDistance = 0.f;
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = "Notify")
	TEnumAsByte<EMovementMode> DashMovementMode = MOVE_None;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	EDashDirectionType DashDirectionType = EDashDirectionType::CrossHair;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FName TargetActorSocket;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FVector TargetActorOffset = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bOffsetIncludeTargetCapsuleRadius = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bStopDashWhenTargetBePortal = false;
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bRestrictTargetActorTypeAutonomousUpdate = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bTransformTargetLocationWhenTargetBePortal = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bTickUpdateDirToCrossHair = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bTickUpdateInverseDir = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bClampCrossHairPitch = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float MinCrossHairPitch = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float MaxCrossHairPitch = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bUseControllerDirection = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	EDashFinishVelocityMode DashFinishVelocityMode = EDashFinishVelocityMode::Zeroing;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FVector DefaultDirection = FVector::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool StopOnArrive = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float StopDistance = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bIgnoreCharacterExceptTarget = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bProjected = false;
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bServerRespectRemoteCancelData = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FMarvelGameplayTagRequirements CollisionTargetTagRequirements;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FGameplayTagContainer BlockAbilityTags;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FGameplayTagContainer CancelAbilityTags;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bUseForceStopDashTag = false;
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bForceBindActorHit_ThreadSafe = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bForceStopWithTimeout = false;
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bForceServerMoveImmediateUpdate = false;
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bForbidPredictingClientMoveBackWhenCollided = false;
};

USTRUCT(BlueprintType)
struct FFluxKinematicBuoyancyPontoonOverride
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float Radius = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FVector Offset = FVector::ZeroVector;
};

USTRUCT(BlueprintType)
struct FInstanceProgressInfo
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TObjectPtr<UFXSystemComponent> FXSystemComponent;
};

USTRUCT(BlueprintType)
struct FLerpCameraSpringArmLengthBodySizeStageCameraExternalScales
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float StageMinus3 = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float StageMinus2 = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float StageMinus1 = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float Stage0 = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float Stage1 = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float Stage2 = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float Stage3 = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float Stage4 = 0.f;
};

USTRUCT(BlueprintType)
struct FMaterialParameterFloatTransition
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FName ParameterName;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	EMaterialParameterValueSource ValueSource = EMaterialParameterValueSource::RangeValues;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FVector2f RangeValues = FVector2f::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bUseAbsoluteTime = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TSoftObjectPtr<UCurveFloat> ExternalCurve;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FName AnimationCurveName;
};

USTRUCT(BlueprintType)
struct FMaterialParameterFloatValue
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FName ParameterName;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float Value = 0.f;
};

USTRUCT(BlueprintType)
struct FRecoveryCostConfig
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	EAmmoClipType CostType = EAmmoClipType::NONE;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	bool bRecoveryMaxCost = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float RecoveryValue = 0.f;
};

USTRUCT(BlueprintType)
struct FRefreshCooldownParams
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	int32 AbilityID = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	ERefreshCooldownType RefreshType = ERefreshCooldownType::Reset;
};

USTRUCT(BlueprintType)
struct FReplaceMaterialInfo
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 ElementIndex = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FMaterialQuery Query;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UMaterialInterface> DefaultMaterial;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UMaterialInterface> TargetMaterial;
};

USTRUCT(BlueprintType)
struct FSetMeshSlotGroupSpec
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTag GroupTag;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FMaterialParameterFloatValue> ScalarParameters;
};

USTRUCT(BlueprintType)
struct FSpringArmControlHandler
{
	GENERATED_BODY()

	// The dump declares no serialised fields.
};

USTRUCT(BlueprintType)
struct FSyncWithMTCacheInfo
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TArray<TObjectPtr<USkeletalMeshComponent>> CachedMeshComponents;
	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TObjectPtr<UAnimInstance> CachedLeaderAnimInstance;
	UPROPERTY(VisibleAnywhere, Category = "Notify")
	TObjectPtr<UAnimInstance> CachedSelfAnimInstance;
};

USTRUCT(BlueprintType)
struct FUpdateMeshSlotGroupSpec
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTag GroupTag;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FMaterialParameterFloatTransition> ScalarParameters;
};

USTRUCT(BlueprintType)
struct FUpperBodyBlendSwitch
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Notify")
	bool UseUpperWhenMoving = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool UseUpperWhenStopping = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool UseUpperWhenJumping = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool UseUpperWhenLanding = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool UseUpperWhenLandingAlready = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool UseUpperWhenIdling = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool UseUpperWhenTurningInPlace = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool UseUpperWhenStopOverIdling = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool UseUpperWhenLandOverIdling = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool UseUpperWhenFlyIdling = false;
};

USTRUCT(BlueprintType)
struct FUpperLayeredBlendConfig
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Notify")
	float Spine_Alpha = 0.f;
	UPROPERTY(EditAnywhere, Category = "Notify")
	TArray<float> Extern_Spine_Alpha;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float Clavicle_L_Alpha = 0.f;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float Clavicle_R_Alpha = 0.f;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bUseSpecialAlphaWhenMoving = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float Spine_Alpha_Moving = 0.f;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float Clavicle_L_Alpha_Moving = 0.f;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float Clavicle_R_Alpha_Moving = 0.f;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bSpineMeshSpaceRotationBlend = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bClavicleMeshSpaceRotationBlend = false;
	UPROPERTY(EditAnywhere, Category = "Notify")
	bool bClavicleMeshSpaceRotationBlend_L = false;
};
