// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Hero_1049.AnimNotifyState_WolverineTimedNiagaraWithAngerParam` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotifyState_TimedNiagaraEffectEx.h"
#include "Curves/CurveFloat.h"
#include "UObject/ObjectPtr.h"
#include "AnimNotifyState_WolverineTimedNiagaraWithAngerParam.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_WolverineTimedNiagaraWithAngerParam"))
class HERO_1049_API UAnimNotifyState_WolverineTimedNiagaraWithAngerParam : public UAnimNotifyState_TimedNiagaraEffectEx
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TMap<FName,TObjectPtr<UCurveFloat>> RageMeterToFXParameters;
};
