// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Hero_1056.AnimNotify_CameraShake_1056` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotify_CameraShake.h"
#include "Hero_1056Types.h"
#include "LegacyCameraShake.h"
#include "Templates/SubclassOf.h"
#include "AnimNotify_CameraShake_1056.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_CameraShake_1056"))
class HERO_1056_API UAnimNotify_CameraShake_1056 : public UAnimNotify_CameraShake
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Notify")
	TMap<EAngelaEnergyLevel,TSubclassOf<ULegacyCameraShake>> ShakeClasses;
};
