// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Hero_1056.AnimNotifyState_TimedFXWithAO_1056` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotifyState_TimedFXWithAO.h"
#include "GameplayTagContainer.h"
#include "AnimNotifyState_TimedFXWithAO_1056.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedFXWithAO_1056"))
class HERO_1056_API UAnimNotifyState_TimedFXWithAO_1056 : public UAnimNotifyState_TimedFXWithAO
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FGameplayTag EnergyTag;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName FXParamName;
};
