// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Hero_1056.Hero_1056Types` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Curves/CurveFloat.h"
#include "GameplayTagContainer.h"
#include "UObject/ObjectPtr.h"
#include "Hero_1056Types.generated.h"

UENUM(BlueprintType)
enum class EAngelaEnergyLevel : uint8
{
	Default = 0,
	Low = 1,
	Mid = 2,
	High = 3,
	Full = 4,
	EAngelaEnergyLevel_MAX = 5,
};

UENUM(BlueprintType)
enum class EAngelaWeaponType : uint8
{
	None = 0,
	Spear = 1,
	Axe_L = 2,
	Axe_R = 3,
	Shield = 4,
	Wing = 5,
	EAngelaWeaponType_MAX = 6,
};

USTRUCT(BlueprintType)
struct FMeshMaterialUpdateInfo
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float DefaultValue;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	TObjectPtr<UCurveFloat> Curve;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	FGameplayTagContainer PauseStatus;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	float ReplaceTime;
};
