// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Hero_1037.Magneto_ANSTimedAttachment` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotifyState_TimedAttachment.h"
#include "Magneto_ANSTimedAttachment.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "Magneto_ANSTimedAttachment"))
class HERO_1037_API UMagneto_ANSTimedAttachment : public UAnimNotifyState_TimedAttachment
{
	GENERATED_BODY()

public:
	// No serialised properties.
};
