// Generated by tools/gen_notify_stubs.py. DO NOT EDIT BY HAND.
using UnrealBuildTool;

public class Hero_1056 : ModuleRules
{
	public Hero_1056(ReadOnlyTargetRules Target) : base(Target)
	{
		// UE 5.3 supports MSVC 14.34-14.38, but a current VS 2022 installs 14.4x. On those,
		// `#if __has_feature(address_sanitizer)` in the engine's own ConcurrentLinearAllocator.h
		// trips C4668, which UE promotes to an ERROR with /we4668 -- so a stock engine plus a
		// current compiler cannot build this plugin at all.
		//
		// Turning the warning off is only half of it: the failure happens while building the
		// SHARED PCH, which is compiled with ENGINE module settings, not ours. Opting out of shared
		// PCHs is what actually moves these translation units onto our own flags. It costs some
		// compile time and changes nothing about the generated code.
		PCHUsage = ModuleRules.PCHUsageMode.NoSharedPCHs;

		// NO UNITY BUILD. Unity concatenates several .cpp files into one translation unit, and the
		// preview implementations are deliberately self-contained -- each carries its own file-local
		// helpers, several of which share a name with another file's. Merged, those become
		// redefinitions. Keeping the files separate is what makes "one .cpp per class, no shared
		// header" a design that holds, and on a module of small stubs the compile-time cost is
		// nothing.
		bUseUnity = false;
		bEnableUndefinedIdentifierWarnings = false;

		PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "GameplayCameras", "GameplayTags", "Marvel" });
	}
}
