// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Hero_1046.AnimNotify_SpawnProjectileFromWeapon` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotify_SpawnProjectile.h"
#include "AnimNotify_SpawnProjectileFromWeapon.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_SpawnProjectileFromWeapon"))
class HERO_1046_API UAnimNotify_SpawnProjectileFromWeapon : public UAnimNotify_SpawnProjectile
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName WeaponSocketName;
};
