// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/NiagaraAnimNotifies.AnimNotifyState_TimedNiagaraEffectWithSpeed` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.
//
// FLATTENED. The game derives this from `UAnimNotifyState_TimedNiagaraEffect`, which stock UE
// marks MinimalAPI -- a subclass in another module fails at LINK time on its
// virtuals. So it derives from `UAnimNotifyState` here and declares that
// ancestor's properties directly. A .uasset tags each property by NAME, not by
// the class that declared it, so the bytes are identical either way -- and the
// ancestor's fields are read from the DUMP, which means you get the GAME's
// version of them, not the smaller stock one.


// NOT PART OF THE PLUGIN, AND NOT BUILDABLE AS ONE.
//
// The game declares this notify inside a module stock UE 5.3.2 already owns, and an asset stores
// a notify by its full path -- so no plugin module can produce the path this class needs. To use
// it you have to add this header to a SOURCE BUILD of that engine module and rebuild it. The
// plugin deliberately does not ship it, because a stub under the wrong path would look correct in
// the editor and resolve to nothing in game.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "Curves/CurveFloat.h"
#include "NiagaraSystem.h"
#include "UObject/NoExportTypes.h"
#include "UObject/ObjectPtr.h"
#include "UObject/SoftObjectPtr.h"
#include "AnimNotifyState_TimedNiagaraEffectWithSpeed.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_TimedNiagaraEffectWithSpeed"))
class NIAGARAANIMNOTIFIES_API UAnimNotifyState_TimedNiagaraEffectWithSpeed : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TSoftObjectPtr<UNiagaraSystem> Template;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName SocketName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector LocationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FRotator RotationOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FVector Scale3D;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bDestroyAtEnd;
	UPROPERTY(EditAnywhere, Category = "Notify")
	float ComponentTimeScale;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TArray<FName> ComponentTags;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUsedTranslucencySortPriority : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 TranslucencySortPriority;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	uint8 bUsedTranslucencySortDistanceOffset : 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float TranslucencySortDistanceOffset;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	TObjectPtr<UCurveFloat> SpeedCurve;
};
