// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/Hero_1042.AnimNotify_PeniParkerAnimSpecialState` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "AnimNotify_PeniParkerAnimSpecialState.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_PeniParkerAnimSpecialState"))
class HERO_1042_API UAnimNotify_PeniParkerAnimSpecialState : public UAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bInAnimSpecialState;
};
