// Generated by tools/gen_notify_stubs.py. DO NOT EDIT BY HAND.
#include "Modules/ModuleManager.h"

// The MODULE NAME is the whole point of this file. A montage stores its notify as
// `/Script/PyAbility_223.<Class>`, and only a module actually named `PyAbility_223` produces that path.
IMPLEMENT_MODULE(FDefaultModuleImpl, PyAbility_223);
