// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/HeroGAS_1023.AnimNotify_SpawnProjectile_102308` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "AnimNotify_SpawnProjectile.h"
#include "AnimNotify_SpawnProjectile_102308.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotify_SpawnProjectile_102308"))
class HEROGAS_1023_API UAnimNotify_SpawnProjectile_102308 : public UAnimNotify_SpawnProjectile
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 ProjectileCount;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	float SpreadAngle;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName WeaponSocketName;
};
