// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/MarvelGameplayCues.AnimNotifyState_ApplyHeroSkinCustomizationToTaggedMesh` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotifyState.h"
#include "AnimNotifyState_ApplyHeroSkinCustomizationToTaggedMesh.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "AnimNotifyState_ApplyHeroSkinCustomizationToTaggedMesh"))
class MARVELGAMEPLAYCUES_API UAnimNotifyState_ApplyHeroSkinCustomizationToTaggedMesh : public UAnimNotifyState
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	FName TargetComponentTag;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bApplyOnBegin;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bRefreshWhileActive;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	int32 PostBeginRefreshTickCount;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Notify")
	bool bRestoreWhenEnd;
};
