// Generated by tools/gen_notify_stubs.py from the Marvel Rivals SDK dump. DO NOT EDIT BY HAND.
//
// This is a STUB. Its job is that a montage authored in a stock UE 5.3.2 editor stores
// the class path `/Script/PyAbility_223.PyAnimNotify_HeratEffect_22301` and the property names the game reads. In
// game that path resolves to the GAME's class, never to this one -- so the property
// NAMES and TYPES below are load bearing and the bodies are not.

#pragma once

#include "CoreMinimal.h"
#include "MarvelAnimNotify.h"
#include "PyAnimNotify_HeratEffect_22301.generated.h"

UCLASS(Blueprintable, hidecategories = Object, collapsecategories,
	meta = (DisplayName = "PyAnimNotify_HeratEffect_22301"))
class PYABILITY_223_API UPyAnimNotify_HeratEffect_22301 : public UMarvelAnimNotify
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Notify")
	int32 AnimStep;
};
